trigger: ["master"]
pr: ["master"]

stages:
 - stage: Lint
   jobs:
     - template: job-fmt.yaml@templates
     - template: job-clippy.yaml@templates
 - stage: Test
   jobs:
     - template: job-test.yaml@templates

resources:
  repositories:
    - repository: templates
      type: github
      name: norse-rs/azure-ci
      endpoint: msiglreith
